### PR TITLE
Use vmsvga + 10MB of VRAM and update JSONs

### PR DESCRIPTION
**Pull request by juadde**
Hello, I tried to warn the user when he use Virtualbox and still align on Vbox recos.
Please let me know if I can do something better.

### CODE REVIEW

**Comment by shibumi** [comment]
This wouldn't change the fact that users will need the additional module right? My problem with that patch is right now, that the module is not included in the kernel, that is necessary for this patch.

Also I have no idea how users on Windows or Mac OS would react with that patch.

**Comment by juadde** [comment]
The video driver has to be installed on the Host, not on the Guest, seems that I need to update the message to be more clear.

**Comment by shibumi** [comment]
Hey, I thought a little bit about this PR:

This host requirement is too risky right now for us. Of course, we could provide a message that users need this vmware module, but what do we do with the people on Mac OS or Windows?

Sorry for turning down your work. But let's close this and focus on other things instead (like qcow2 cloud images).

**Comment by juadde** [comment]
Yes, no problem for me, I just wanted to highlight something here:

The warning message is about a **Guest** requirement, not a **Host** requirement.
Running the arch-box with Virtualbox on Windows (10) or on Linux (Arch) had the exact same effect on my setup (I have no Mac to test this).

Let me just describe it a little more here if we want to switch to this behavior in the future:
- The box is actually built with the VBOXVGA driver, this driver is outdated but works well with arch-box when X11 **within the box** is installed (with a DE for example)
- The "new" VirtualBox driver is VBOXSVGA, and work exactly as VBOXVGA, with improved performances, however it is used by default for Windows >= 7, not Linux Guests (I honestly don't know why, VBOXSVGA is working quite well with the arch-box)
- The "default" graphics controller for Linux guests is VMSVGA, but then, **inside the Guest** you have to install the corresponding xf86-video-vmware, and resizing etc. does not work in my case
- The NONE option is actually working well with the Box, but you loose the ability to interact from the GUI - even from the console (SSH is working well, of course)

So basically when using VBOXVGA / VBOXSVGA there is no supplementary driver to install, and Guest dynamic resizing etc. works well.
When using VMSVGA, there is a supplementary driver to install in the Guest ([xf86-video-vmware](https://www.archlinux.org/packages/extra/x86_64/xf86-video-vmware/) - at least on Arch), and on my setup Guest resizing was not working properly (I was using deepin as desktop environment - I did not test with the latest Virtualbox additions).

I should update the archlinux wiki with some insights for virtualbox.
Please keep in mind that this option is only available in Virtualbox > 6.0, when using Virtualbox < 6.0, the graphic controller is automatically switched to VBOXVGA as it is the only driver available.

I completely agree with the closure of this PR, especially because of the lack of dynamic resizing.

I will test from time to time with new versions of Virtualbox the settings and re-open a PR if they fix the resizing as this would be the preferred way to go.

[VirtualBox documentation](https://www.virtualbox.org/manual/ch03.html#settings-display)

**Pull request closed without merging**
