### PR TITLE
Improve pacstrap download speed with reflector

### PR DESCRIPTION
**Pull request by tteaka**
I put this in my fork, to speed up the build of my box.
Please, as you don't have automated test for images, try it first before a potential approvement.
I tested it only with virtualbox.

### CODE REVIEW

**Comment by shibumi** [comment]
lgtm, can you format your code with `shfmt`? Looks like our shell-format-validation is failing.

**Comment by tteaka** [comment]
The shfmt download link (https://github.com/mvdan/sh/releases/download/null/shfmt_null_linux_amd64) is dead.

**Comment by tteaka** [comment]
Sorry for the noise, it seems that this [line](https://github.com/archlinux/arch-boxes/blob/master/generic-ci.sh#L27) in `generic-ci.sh` failed when I opened the PR.

**Comment by shibumi** [comment]
lgtm

**Pull request merged**
