### PR TITLE
install: use btrfs with zstd compression

### PR DESCRIPTION
**Pull request by coderobe**
this *may* help with size

needs to be tested before merging

### CODE REVIEW

**Comment by coderobe** [comment]
this uses the default compression level, which may be 1 - a higher level will yield better results. not sure which one to pick, though 6 looks promising, maybe even higher. faster and smaller than the default (zlib) at any level

**Comment by shibumi** [comment]
closing this for now, due to the fact that btrfs images are bigger (even with dedup + zstd compression). Looks like this has something to do with btrfs' overhead.

**Comment by coderobe** [comment]
I don't think btrfs overhead is at play here. I reckon the zeroing might not work as expected.

**Comment by shibumi** [comment]
possible, feel free to reopen if you have a new idea. We'll have soyuz for testing at least one month from now.

**Pull request closed without merging**
